### ISSUE TITLE
youtube api key v3 

### ISSUE THREAD

**Issue by iiLizxMohammed2** [Delivator/discord-bot#15]
well, when i run the setup.js file and wehn ask me the token i clicked on enter and its fine but when ask about the api and i clicked on enter but the console showed me this error : UnhandledPromiseRejectionWarning: ReferenceError: error is not defined
    at got.then.catch (F:\newbot\setup.js:42:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1568) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1568) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
please help

**Comment by Delivator** [comment]
Thanks for reporting the bug!
It was a simple bug that has been fixed with f7e464cd1901034afe33dc5991ff3200aba09bdd.
